name: rick_and_morty
description: "Rick and morty app"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1

  # API & Networking
  retrofit: ^4.7.2
  dio: ^5.9.0

  # Local Database & Persistence
  drift: ^2.28.2                
  sqlite3_flutter_libs: ^0.5.39 
  path_provider: ^2.1.5         
  path: ^1.9.1                
  cached_network_image: ^3.4.1  
  shared_preferences: ^2.5.3

  # Code Generation
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Routing
  auto_route: ^10.1.2

  # Dependency Injection
  get_it: ^8.2.0
  injectable: ^2.5.2
  injectable_generator: ^2.8.1

  # UI
  cupertino_icons: ^1.0.2

  # Utils
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  auto_route_generator: ^10.2.4
  retrofit_generator: ^10.0.5
  drift_dev: ^2.28.3          

  # Linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
